apiVersion: v2
name: n8n-node
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: plural-apps-common
    version: ~4
    repository: "s3://plural-chart-server/stable"
